### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by iwiwi** [pfnet/chainermn#77]
This issue is the central place to discuss the future plans. Any suggestion and contribution are appreciated. We continuously update the following task list. 

## Performance

* [ ] Asynchronous SGD (@keisukefukuda)
* [ ] Double buffering (@shu65)

## Examples

* [ ] Seq2seq example (@keisukefukuda)
* [ ] DCGAN
* [ ] ChainerRL
